name=input("Enter the name of student:")
grade=input("Enter the grade of the student :")
age = int(input("enter the age"))
email=input("enter the email of the student :")
ph_no= input("enter the phone number of the student")
print("Student Identity Card")
print(name)
print(grade)
print(age)
print(email)
print(ph_no)